### ISSUE TITLE
[PE-D] Accept Invalid name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T09-2/tp#191]
Add command allow name to have number

Input: add n/101 e/ben123@gmail.com m/CS2103T T12 p/91238456 h/@BenIsHere r/Overseas

Expectation: Reject with error message

Actual:

![Screenshot 2021-10-29 at 5.25.02 PM.png](https://raw.githubusercontent.com/jeromewjj/ped/main/files/e9afffd8-46c1-43fa-9e96-346026588ecc.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: jeromewjj/ped#8

**Comment by tanruiquan** [comment]
Should we allow names to have numbers?
